### ISSUE TITLE
Makefile support ARM linux 

### ISSUE THREAD

**Issue by seanshpark** [Samsung/jerryscript#1]
Hi,
I'm adding this issue as a todo item to support arm-linux and with maybe add other architecture-platform easier. And as there is no issue, I want to start with this not-urgent one.
* platforms that we can support: linux, nuttx, darwin, ...
* architectures: armv7, armv6, i686, x86_64, ...
* type: debug, release, ...
* mods: cp cp_minimal, mem_stats, ...
* boards (maybe for embedded): stm32f3, stm32f4, ...

**Comment by egavrin** [comment]
Cross compilation support added 444bd32d50a059e050442aa885c9c9eda0d227cc

**Comment by seanshpark** [comment]
Thank you!
I've checked with arm-linux-eabi-gcc version 4.7 build with
```
make debug.linux TOOLCHAIN=./build/configs/toolchain_linux_armv7l-el.cmake
```
with 71bac03d5133043a6bfd83c044333b897dc1ab95 (as of 1 July) and got this problem;
```
jerry-core/lit/lit-strings.cpp:378:81: error: conversion to ‘lit_utf8_byte_t {aka unsigned char}’ from ‘int’ may alter its value [-Werror=conversion]
```

**Comment by egavrin** [comment]
@seanshpark I'll check. Thank you!

**Comment by egavrin** [comment]
@seanshpark please check #291

**Comment by seanshpark** [comment]
@egavrin thank you, I'll wait #291 to land.

**Comment by egavrin** [comment]
pushed as 56e7ead9f9e4e5112bd38bffdbac093fe274992a

**Comment by seanshpark** [comment]
Just for information, I'm on https://github.com/Samsung/iotjs/issues/117

**Comment by seanshpark** [comment]
Thank you!
