### ISSUE TITLE
jerry_api_get_object_field_value doesn't return what it claims to

### ISSUE THREAD

**Issue by grgustaf** [Samsung/jerryscript#1041]
Contrary to the documentation for the function, this doesn't seem to return false when the field doesn't exist. This appears to be because the underlying call to ecma_op_general_object_get will just return an undefined value instead of an error, if the property doesn't exist.

A simple fix would be to change the docs, but I think the behavior as stated is useful; I'm trying to use it. :) For now, I can work around it by checking for undefined value.

**Comment by LaszloLango** [comment]
@grgustaf, thanks for the bug report. I uploaded a fix for the issue (#1042). Please check.
