### ISSUE TITLE
Why does jerryscript use static heap reservation?

### ISSUE THREAD

**Issue by esevan** [Samsung/jerryscript#1048]
Hi, I'm recently interested in optimizing the memory management technique in lightweight JS engine. JerryScript uses the special policy for memory management, i.e. static heap reservation, and compressed pointer unlike other js engines such as duktape, v7, and mujs. 
 As mentioned in IoT.js issue (https://github.com/Samsung/iotjs/issues/211), this heap reservation harms the other memory allocation in constrained memory environment. Why does jerryscript maintain this static heap reservation despite of that problem?

IMHO, the reasons why jerry statically reserves heap region are 

1. to use compressed pointer since it would save the memory by reducing the size of data structure including object pointer. In order to use compressed pointer, the contiguous memory region should be guaranteed so as to decompress that pointer via only base memory address (i.e. this base memory address and contiguous memory region guaranteed by static memory reservation). 

2. The second reason is for the efficient management for the chunk (8 byte memory region). Using malloc / free as the other js engines do critically wastes the memory since malloc maintains chunk metadata (at least ptr, size for later free) even though chunk size is small so that it doubles memory usage in allocating small chunks such as 8-byte chunks, the most frequently used memory unit in jerryscript.

3. The last reason that I guess is to give such privilege to JS engine. The application running on the jerryscript could terminate by the out of memory error, but it MUST NOT terminate during run on the jerryscript code (It's about reliability issue of the engine).

Is there other reason of the design to use static heap reservation?
Appreciated with Any opinions. Thanks.

**Comment by zherczeg** [comment]
I think this is a good summary of the reasons of using a static heap and an own memory allocator.
