### ISSUE TITLE
Close dead branches

### ISSUE THREAD

**Issue by zherczeg** [Samsung/jerryscript#1092]
Currently there are 26 open branches in Jerry. Several of them are 8 months old, and unlikely to be updated. Since we moved to fork model, it would be good to only have a master branch, and perhaps each release could have one. What do you think?

**Comment by LaszloLango** [comment]
+1

**Comment by akiss77** [comment]
There are certainly some dead feature branches in origin, which could and should be removed. There are some others which are somewhat questionable, however: e.g., `demo_soscon2015` may be one which we might want to keep for a longer period of time to help replicability. So, I think a case-by-case investigation is needed. But overall, sure, merged or abandoned feature & fix branches should be removed.
(And let's not forget to keep `gh-pages`...)

**Comment by zherczeg** [comment]
I think the author of each branch should decide whether his/her own branches are needed. This is the first step. I have already dropped my dead branches.

**Comment by lemmaa** [comment]
CC: @egavrin @sand1k @ruben-ayrapetyan @seanshpark @chunseoklee @ILyoan @wateret , Please check the branches you have created, if you have. Thank you in advance. :)

**Comment by wateret** [comment]
Nothing to keep for me :D

**Comment by egavrin** [comment]
Slightly reduced this number to 13  ^_^

**Comment by seanshpark** [comment]
nothing for me :)

**Comment by seanshpark** [comment]
Removed what I created. I think `gh-pages` should exist.

**Comment by LaszloLango** [comment]
@zherczeg, I think we removed the unnecessary branches. Please check that we can close this issue or not.

**Comment by zherczeg** [comment]
remotes/origin/demo_soscon2015
  remotes/origin/fix339
  remotes/origin/gh-pages
  remotes/origin/iotjs
  remotes/origin/refactor-lit-storage-rebased
  remotes/origin/snapshot-nuttx-dev
  remotes/origin/targets-rpi2

I think these branches are outdated and could be closed.

**Comment by LaszloLango** [comment]
@zherczeg, we must keep 'gh-pages'

**Comment by seanshpark** [comment]
In case who don't know 'gh-pages' , it's the http://samsung.github.io/jerryscript/

**Comment by zherczeg** [comment]
I forgot to remove remotes/origin/gh-pages, it is needed of course.

**Comment by zherczeg** [comment]
remotes/origin/fix339 by Ilyong Cho - the issue works here
remotes/origin/targets-rpi2 - @seanshpark a phony target added in 6th of january. Is it needed?
remotes/origin/snapshot-nuttx-dev - Chunseok Lee - The new API has proper strict mode support for snapshots, so I don't think this workaround is still needed.
remotes/origin/iotjs - Peter Gal - data fix - does it still needed? (patch was made in 16th of september)

**Comment by seanshpark** [comment]
> remotes/origin/targets-rpi2

it is ok to remove :)

**Comment by lemmaa** [comment]
cc: @ILyoan @chunseoklee

**Comment by akosthekiss** [comment]
@ILyoan fix339?
@galpeter iotjs?
@chunseoklee snapshot-nuttx-dev?
(What about removing these if no answer comes back by, say, end of August?)

**Comment by galpeter** [comment]
@akosthekiss @zherczeg the `iotjs` branch is not needed, we can delete it

**Comment by akosthekiss** [comment]
After careful review, the snapshot-nuttx-dev branch turned out not to contain useful changes anymore, thus was deleted. As all targeted branches were removed, we can close this issue.
