### ISSUE TITLE
Fix NuttX target

### ISSUE THREAD

**Issue by LaszloLango** [Samsung/jerryscript#1202]
Nuttx target isn't working. It must be updated to the latest API and improve the how-to documentation.

**Comment by LaszloLango** [comment]
cc: @bzsolt, @robertsipka

**Comment by seanshpark** [comment]
Anyone working on this? @LaszloLango, can you share your thoughts?

**Comment by LaszloLango** [comment]
@bzsolt has something done with this task. Not sure what is the current progress or status of his work.

**Comment by FelipeF1198** [comment]
444
