### ISSUE TITLE
Building JerryScript for ESP8266 fails with: Missing jerry.h

### ISSUE THREAD

**Issue by slaff** [Samsung/jerryscript#1211]
I tried to build JerryScript for ESP8266 by following the [readme](https://github.com/Samsung/jerryscript/blob/master/targets/esp8266/readme.md) file. I have setup the ESP8266 toolchain but when I try to compile JerryScript I end up with the following error:

```
[  0%] Building C object CMakeFiles/release.external-entry.dir/targets/esp8266/source/jerry_extapi.c.obj
/xyz/dev/jerryscript/targets/esp8266/source/jerry_extapi.c:19:30: fatal error: jerry-core/jerry.h: No such file or directory
 #include "jerry-core/jerry.h"
                              ^
compilation terminated.
```

I could not find the `jerry.h` file in the project. Any ideas what am I doing wrong?

**Comment by tilmannOSG** [comment]
PR #1212 has landed, closing this issue. No idea why GitHub didn't do this automatically.
