### ISSUE TITLE
Add jerry_... APIs to create NaN and inf

### ISSUE THREAD

**Issue by martijnthe** [Samsung/jerryscript#1247]
Would it make sense to have wrappers for `ecma_make_nan_value()` and `ecma_number_make_infinity()` ?

**Comment by zherczeg** [comment]
Do you mean public API wrappers? Technically it is possible. However I somehow feel that these functions would be better suited for math libraries, since you can convert doubles to jerry numbers.

It seems gnu math.h has them:
https://www.gnu.org/software/libc/manual/html_node/Infinity-and-NaN.html

**Comment by martijnthe** [comment]
Yeah, I mean public API wrappers indeed.
I couldn't find an easy way to create a `NaN` value.

**Comment by zherczeg** [comment]
Please check PR #1252

**Comment by martijnthe** [comment]
Looks good, thanks much!

**Comment by LaszloLango** [comment]
IMHO, We should consider to add jerry_value_is_infinite and jerry_value_is_nan as well.

**Comment by akosthekiss** [comment]
The PR that added the two requested functions has been landed some days ago. Shall we close this issue or shall we keep it open as a reminder that two more API functions could be added, as suggested by @LaszloLango ? (Anyone for or against those two funcs?)

**Comment by zherczeg** [comment]
I think I will close it, and can be reopened if more work is done.
