### ISSUE TITLE
for-in fails on some code

### ISSUE THREAD

**Issue by yichoi** [Samsung/jerryscript#1300]
Below code fails on `JERRY_ASSERT` in debug mode,
(Assertion 'context_p->stack_depth == context_p->context_stack_depth' failed)
and returns wrong result in release mode.
("prop" is not assigned into array[0][0])

```
var array = [ [0] ];
var obj = { prop : "" };
var i = 0;
for (array[0][i] in obj)
    /* do something */ 
assert(array[0][0] == "prop");
```

**Comment by bzsolt** [comment]
Merged at https://github.com/Samsung/jerryscript/commit/9f65b7601336430600bd063c5e3288f5323227f3
