### ISSUE TITLE
Nominating Tilmann Scheller (@tilmannOSG) to become a JerryScript maintainer

### ISSUE THREAD

**Issue by zherczeg** [Samsung/jerryscript#1315]
I would like to nominate Tilmann Scheller (@tilmannOSG) to become a member of the Steering Committee. Tilmann has been leading the SRUK OSG JerryScript team for more than 1.5 years now and has been actively participating in the community through reviews and discussions and also contributed several patches in the last months. He helped organize the first JerryScript workshop earlier this year and has given several talks to promote JerryScript at conferences like FOSDEM and the OpenIoT Summit.

Any seconds?

Thanks in advance!

**Comment by LaszloLango** [comment]
+1

**Comment by bzsolt** [comment]
+1

**Comment by minjung978** [comment]
+1

**Comment by robertsipka** [comment]
+1

**Comment by dbatyai** [comment]
+1

**Comment by luisbg** [comment]
+1 (for what it's worth)
:smile:

**Comment by akosthekiss** [comment]
+1

**Comment by minjung978** [comment]
+1

**Comment by somang-park** [comment]
+1 (believe Tilmann)

**Comment by lemmaa** [comment]
+1
