### ISSUE TITLE
Nominating Robert Sipka (@robertsipka) to become a JerryScript committer

### ISSUE THREAD

**Issue by zherczeg** [Samsung/jerryscript#1321]
I would like to nominate Robert Sipka to become a committer. He already has 39 patches:

#1317 Add missing jerry-libm include path to jerry-core target.
#1291 Remove unused JERRY_ENABLE_PRETTY_PRINTER from the build system.
#1263 Remove unused ecma-helpers functions
#1259 Remove needless toolchain files and variable settings.
#1238 Remove compact profile.
#1231 Complete the getting-started documentation after the build-system update.
#1230 Comment fixes which are left behind after the API update.
#1229 Change the CONFIG_ECMA_NUMBER_TYPE default value to CONFIG_ECMA_NUMBER_FLOAT64.
#1228 Build fix for RIOT target after the modifications of the build system
#1192 Re-thinking the build system to bring it more into line with the conventions.
#1159 Build fix for ALL_IN_ONE and COMPILER_DEFAULT_LIBC 
#1133 Rename 'jerry_api_' prefix to 'jerry_' in the main-riotos.c file
#1130 Added target to compile RIOT-OS against jerryscript
#1115 Insert parameters between the pair of parentheses in the JERRY_MIN and JERRY_MAX definitions.
#1114 Use 'ecma_get_float_from_value' instead of 'ecma_get_number_from_value' in the ToString operation.
#1098 Optimising the ToString operation
#1066 Unify the condition form within the asserts
#1043 Initialize the timeval struct fields, because the gettimeofday() may not fill these.
#1040 Unified the commenting form of the internal properties and removed the unused types.
#1036 Improve the string descriptor.
#1033 Check whether the aligned pointers value of the internal properties can be stored directly
#1026 Store aligned pointers directly in ecma_value_t if it is possible. 
#1020 Don't use pointer compression where the ecma_value can store pointer value directly.
#1014 Use 'ECMA_VALUE_CAN_STORE_UINTPTR_VALUE_DIRECTLY' instead of comparision with 'sizeof'
#1010 Set the correct pointer value in 'ecma_copy_ecma_string' function.
#1007 Remove the unused LIT_STRING_HASH_LAST_BYTES_COUNT define macro
#938 Warning fixes. 
#935 Build fix for mbedk64f target
#921 Warning fix for ALL_IN_ONE.
#916 Add another argument for the JERRY_STATIC_ASSERT with the description of the assert statement.
#885 Warning fixes.
#876 Eliminate cpp featureset
#863 Use 'static inline' for function definitions that are in header files.
#862 Use simple types instead of reference types. 
#861 Use type cast to avoid conversation error with C99 standard.
#860 Add forward declaration for mem_pool_chunk struct.
#859 Merge the js-parser and parser files
#851 Remove unnecessary variable length arrays.
#838 Fix the correct number of command line arguments check.

**Comment by akosthekiss** [comment]
+1

**Comment by LaszloLango** [comment]
+1

**Comment by lemmaa** [comment]
+1

**Comment by bzsolt** [comment]
+1

**Comment by tilmannOSG** [comment]
+1

**Comment by egavrin** [comment]
+1

**Comment by dbatyai** [comment]
+1

**Comment by zherczeg** [comment]
Congratulations!
