### ISSUE TITLE
Nominating Young-il Choi (@yichoi) to become a JerryScript maintainer

### ISSUE THREAD

**Issue by zherczeg** [Samsung/jerryscript#1325]
I would like to nominate Young-il Choi to becoma a JerryScript maintainer. He already has 10 patches and fixed several complicated bugs.

#1310 vm_op_set_value should be able to throw error when ecma_op_to_string throws
#1308 SplitMatch operation should not set its return array element with [[Put]]
#1301 Fix bug in for-in bytecode replacement
#1293 FunctionExpression name binding should be immutable
#1287 Eval called as a bound function should be indirect eval 
#1285 [[DefaultValue]] should be called twice when setting object as Array length
#1283 Numbers should be permitted as property name in object literal
#1281 Make jerry shell more intuitive
#1279 Remove unnecessary empty value check code
#1276 Regexp.prototype.exec should generate return array with [[DefineOwnProperty]], not [[Put]]

**Comment by tilmannOSG** [comment]
+1

**Comment by akosthekiss** [comment]
+1

**Comment by LaszloLango** [comment]
+1

**Comment by zherczeg** [comment]
Congratulations!
