### ISSUE TITLE
Array constructor using ecma_lenght_t for length argument

### ISSUE THREAD

**Issue by dbatyai** [Samsung/jerryscript#133]
Currently, the array constructor takes ecma_length_t, which is an uint16, as it's length argument, even though the length of an array can be an uint32. The two should be compatible, so we should either change ecma_length_t to be uint32, or change the array constructor to take uint32 for length.

**Comment by galpeter** [comment]
IMHO this can be closed now as the `ecma_length_t` is now a `uint32_t`.
