### ISSUE TITLE
Math.random() returns range [0, 0.5) instead of [0, 1.0]

### ISSUE THREAD

**Issue by unwiredben** [Samsung/jerryscript#1414]
This was reported on Pebble forums - https://forums.pebble.com/t/rocky-js-math-random-bug/25359

It looks like the problem was introduced with https://github.com/Samsung/jerryscript/commit/6d6c913bdc3bb08e2937691f75449cf248b1a790

The range of the rand() function in jerry-libc is only the positive int32_t values.  However, the code in ecma_builtin_math_object_random assumes the range of rand() is the full uint32_t space, since RAND_MAX is > 0x10000.

**Comment by akosthekiss** [comment]
#1417 is aiming at solving the issue. Note however, that according to [ES5.1](http://www.ecma-international.org/ecma-262/5.1/#sec-15.8.2.14), `Math.random()` must return numbers in the interval `[0,1)`, not `[0,1]`.
