### ISSUE TITLE
jerry save-snaphot-for-global hangs

### ISSUE THREAD

**Issue by nkolban** [Samsung/jerryscript#1437]
I build Jerry on Linux but when I run:

```
./jerry --save-snapshot-for-global t.js output.snp
```

The program just hangs/loops.  If there are additional diagnostics I can run, please let me know.

**Comment by LaszloLango** [comment]
We are testing snapshot feature for every commit in Travis CI and works fine in our test environment.
Could you provide more information? What is in "t.js"? What is the version of JerryScript you are working on? What is your current architecture, x86_64?

**Comment by nkolban** [comment]
Thanks for the response.   Here are the details:

I am building on Ubuntu on an x86-64.

Jerry report as v1.0 (ffaca58)

It built 100% cleanly from a github extract I performed on 2016-11-16 from master.

I tried to run against a variety of JavaScript source files.  My current source file is minimal with:

```
print("hello");
```

**Comment by zherczeg** [comment]
I think the parameter order is worng. Swap t.js and output.snp.

**Comment by nkolban** [comment]
Aha!!  That makes sense ...  now when I run I get the following:

```
$ ./jerry --save-snapshot-for-global output.snp t.js
Script Error: Error
```

My goodness ... we sure love mystery in this project :-)

**Comment by LaszloLango** [comment]
IMHO, wrong parameter order should not hang the engine. We must fix this.

**Comment by zherczeg** [comment]
You need to compile in debug mode or enable error messages to get nice output.

**Comment by zherczeg** [comment]
(JERRY_ENABLE_ERROR_MESSAGES define must be enabled)
