### ISSUE TITLE
No reference error when the variable is not an argument

### ISSUE THREAD

**Issue by galpeter** [Samsung/jerryscript#154]
Consider the following code:
```javascript
try {
    xxxx;
} catch(e) {
    print(e);
}
```
Will *not print* out the expected `ReferenceError` string. But if we change the code in a way that the `xxxx` variable is part of an argument list then the exception is correctly raised.

So using the following code:
```javascript
try {
    print(xxxx);
} catch(e) {
    print(e);
}
```
Will *print* out the expected `ReferenceError` string.

###### Jerry version:
    Checked revision: ac87616f0
    Build: debug.linux

**Comment by egavrin** [comment]
Works on master (f17f785b6ec0c71c2ef37e4e80a98aff1eff0963)
