### ISSUE TITLE
Run the official ECMAScript (ECMA-262) conformance suite.

### ISSUE THREAD

**Issue by LaszloLango** [Samsung/jerryscript#158]
We should be test engine on the original testsuite without any modification. Issues that have to be solved for this:

 - [x] RegExp engine #27 
 - [x] Unicode support #49 
 - [x] Able to parse JS files from 70 Kbyte to 150 Kbyte
 - [x] Implement for-in loop #51
 - [x] Fix the for loop bug with function calls in the iteration part #156 

These are only the currently known issues, there could be more.

### Testsuite
 [Test262](https://github.com/tc39/test262)

**Comment by zherczeg** [comment]
After the fixes I tried to run the official test suite, but there is an out-of-memory error. The sta.js and testIntl.js is too much for Jerry. Could we extend the memory amount to a few megabytes?

**Comment by egavrin** [comment]
The main issue, right now is testIntl.js and 
Currently, the only changes for me is make `testIntl.js` empty and remove `test/suite/intl402/*`.
