### ISSUE TITLE
WebAssembly and JerryScript

### ISSUE THREAD

**Issue by lemmaa** [Samsung/jerryscript#204]
Today, I read an article about WebAssembly.
[Google, Microsoft, Mozilla And Others Team Up To Launch WebAssembly, A New Binary Format For The Web](http://goo.gl/RlVCbi)

What should we do for JerryScript with wasm?
Is it valuable for current target segment of JerryScript? or need to include to future roadmap?
Let’s discuss about it.

**Other references**
* [https://github.com/WebAssembly/design/blob/master/HighLevelGoals.md]
* [https://brendaneich.com/2015/06/from-asm-js-to-webassembly/]

**Comment by zherczeg** [comment]
We can repoen this issue if we start working on webassembly.

**Comment by haochenli** [comment]
I personally think that WebAssembly is a complement for Jerryscript, so do we have any plan to support it?
