### ISSUE TITLE
Missing standard time functions in jerry-libc

### ISSUE THREAD

**Issue by szledan** [Samsung/jerryscript#213]
For Date object implementations we need few time functions and variables, example: `localtime_r`, `gmtime_r`, `daylight` for [1] functions.

These are system dependent features.
Could we somehow use the standard `<time.h>`? 

[1] http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.7

**Comment by rtakacs** [comment]
The following test262 conformance tests fail because we don't support TZA:
```
15.9.3/S15.9.3.1_A5_T1.js
15.9.3/S15.9.3.1_A5_T2.js
15.9.3/S15.9.3.1_A5_T3.js
15.9.3/S15.9.3.1_A5_T4.js
15.9.3/S15.9.3.1_A5_T5.js
15.9.3/S15.9.3.1_A5_T6.js
```

**Comment by ruben-ayrapetyan** [comment]
@rtakacs, could you, please, provide more details on how should Date built-in's implementation be changed to fix the tests?
