### ISSUE TITLE
Build for nuttx problem, undefined reference to 'setjmp' and 'longjmp'

### ISSUE THREAD

**Issue by seanshpark** [Samsung/jerryscript#231]
With latest JerryScript, cannot build for nuttx cause of
```
jerry-core/parser/js/parser.cpp:2917: undefined reference to `setjmp'
jerry-core/parser/js/syntax-errors.cpp:67: undefined reference to `longjmp'
```

How to reproduce: with iotjs build for nuttx. Get latest iotjs source.
```
cd iotjs
git pull

./tools/build.py --buildtype=release \
--target-arch=arm --target-os=nuttx \
--nuttx-home=/home/(...)/harmony/nuttx/nuttx \
--buildlib --no-checktest
```
replace `--nuttx-home` value with your nuttx folder.
Please refer https://github.com/Samsung/iotjs/wiki/Build-for-NuttX page.

**Comment by ruben-ayrapetyan** [comment]
@seanshpark, thank you for clarification of compiler options.

Could you, please, check size of `jmp_buf` buffer, used for storage of registers?

If `jmp_buf` size is enough for all registers, maybe, issue is not directly related to setjmp / longjmp. Could you, please, describe how to reproduce the failure? I'll try to figure out what is the cause.

> BTW, can you please describe how's your build and test environment? 
In pre-commit testing archive libraries are built, but linkage is not performed. So, pre-commit testing passes successfully.

**Comment by seanshpark** [comment]
@ruben-ayrapetyan , I'm not sure how to check jmp_buf size. if I search the code, I get 
```
typedef uint64_t jmp_buf[12];
```

How to reproduce;
* get iotjs gpio development branch from my repo.
```
git checkout -b seanshpark-gpio master
git pull https://github.com/seanshpark/iotjs.git gpio
```
* get latest nuttx patch (I've uploaded it today), as you know it's described in https://github.com/Samsung/iotjs/wiki/Build-for-NuttX
* please build debug version. release won't show any message
* test sample application is now somewhat ready but not quite done so I've added to iotjs-app repo.
* copy blinkled folder to sd-card
* insert sd-card to STM32 BB board
* run iojs with led.js
* memory is critical factor.
   * jerry heap is set to 80K and led.js uses about 72K.
   * CCM RAM is also used for BSS so that 80K heap can be possible. 
   * iotjs stack is about 20K and if less than that, parser won't work
   * system heap is almost at the limit so if few more k-bytes are used then iotjs won't work.

**Comment by seanshpark** [comment]
one more thing, file path for set_jmp is
```
nuttx/configs/stm32f4discovery/src/stm32_jerry-hf.S
```

**Comment by seanshpark** [comment]
@ruben-ayrapetyan , 
I'm don't know how to measure `jmp_buf. what I see from the source is
```
typedef uint64_t jmp_buf[12];
```

How to reproduce;
1) get latest iot.js
2) build for nuttx, follow https://github.com/Samsung/iotjs/wiki/Build-for-NuttX in debug version 
3) edit nuttx/configs/stm32f4discovery/src/stm32_jerry-hf.S file so to enable `vstm` and `vldm`
4) build nuttx, flast to stm board
5) run very simple code, such as
```
console.log("hello world");
```

p.s. I've just deleted last message. how to reproduce was not correct.

**Comment by ruben-ayrapetyan** [comment]
@seanshpark,
size of the `typedef uint64_t jmp_buf[12];` buffer is 96 bytes that is not enough, because, actually, there are 10 * 4 + 16 * 4 = 104 bytes stored. Maybe, it is the cause of the issue.

**Comment by seanshpark** [comment]
@ruben-ayrapetyan , I've changed it to `typedef uint64_t jmp_buf[14];` and still same error.
but it was the sequence of push and pop. below code works.
```
        .global setjmp
        .type setjmp, %function
        .syntax unified
        .thumb
        .thumb_func
setjmp:
        /* Save registers in jump buffer.  */
        vstm    r0!, {s16 - s31}
        sub     r0, r0, #64     // + 16 * 4 = 64 bytes
        stmia   r0!, {r4, r5, r6, r7}
        mov     r1, r8
        mov     r2, r9
        mov     r3, r10
        mov     r4, fp
        mov     r5, sp
        mov     r6, lr
        stmia   r0!, {r1, r2, r3, r4, r5, r6}
        sub     r0, r0, #40
        /* Restore callee-saved low regs.  */
        ldmia   r0!, {r4, r5, r6, r7}
        /* Return zero.  */
        mov     r0, #0
        bx      lr
        .size setjmp, . - setjmp


        .global longjmp
        .type longjmp, %function
        .syntax unified
        .thumb
        .thumb_func
longjmp:
        /* Restore High regs.  */
        vldm    r0!, {s16 - s31}
        add     r0, r0, #16
        ldmia   r0!, {r2, r3, r4, r5, r6}
        mov     r8, r2
        mov     r9, r3
        mov     r10, r4
        mov     fp, r5
        mov     sp, r6
        ldmia   r0!, {r3} /* lr */
        /* Restore low regs.  */
        sub     r0, r0, #40
        ldmia   r0!, {r4, r5, r6, r7}
        vstm    r0!, {s16 - s31}
        sub     r0, r0, #64     // + 16 * 4 = 64 bytes
        /* Return the result argument, or 1 if it is zero.  */
        mov     r0, r1
        bne     1f
        mov     r0, #1
1:
        bx      r3
        .size longjmp, . - longjmp
```
the sequence in jerry-libc is opposite. have you checked with target board?
I'll make a small PR for [12] to [14].

**Comment by ruben-ayrapetyan** [comment]
> @ruben-ayrapetyan , I've changed it to typedef uint64_t jmp_buf[14]; and still same error.
but it was the sequence of push and pop. below code works.

@seanshpark, the `jmp_buf` should be defined in `setjmp.h` in `nuttx/nuttx/include` folder.

**Comment by ruben-ayrapetyan** [comment]
Seems that code below writes {s16 - s31} and then overwrites them with {r4, r5, r6, r7}.
So, because of the changes, maybe it doesn't overflow `jmp_buf`, but maybe context wouldn't be restored successfully with the code:

```
     /* Save registers in jump buffer.  */
        vstm    r0!, {s16 - s31}
        sub     r0, r0, #64     // + 16 * 4 = 64 bytes
        stmia   r0!, {r4, r5, r6, r7}
```

**Comment by ruben-ayrapetyan** [comment]
A test that leads to call of `longjmp` is a test that raises `SyntaxError`.

For example:
```
try
{
  eval ('var var;');
  assert (false);
}
catch (e)
{
 assert (e instanceof SyntaxError);
}
```

**Comment by seanshpark** [comment]
@ruben-ayrapetyan 
I fixed some mistake and the last code is 
```
        .global setjmp
        .type setjmp, %function
        .syntax unified
        .thumb
        .thumb_func
setjmp:
        // Save registers in jump buffer.
        vstm    r0!, {s16 - s31}
        sub     r0, r0, #64     // + 16 * 4 = 64 bytes
        stmia   r0!, {r4, r5, r6, r7}
        mov     r1, r8
        mov     r2, r9
        mov     r3, r10
        mov     r4, fp
        mov     r5, sp
        mov     r6, lr
        stmia   r0!, {r1, r2, r3, r4, r5, r6}
        sub     r0, r0, #40
        // Restore callee-saved low regs.
        ldmia   r0!, {r4, r5, r6, r7}
        // Return zero.
        mov     r0, #0
        bx      lr
        .size setjmp, . - setjmp


        .global longjmp
        .type longjmp, %function
        .syntax unified
        .thumb
        .thumb_func
longjmp:
        // Restore High regs.
        add     r0, r0, #16
        ldmia   r0!, {r2, r3, r4, r5, r6}
        mov     r8, r2
        mov     r9, r3
        mov     r10, r4
        mov     fp, r5
        mov     sp, r6
        ldmia   r0!, {r3} // lr
        // Restore low regs.
        sub     r0, r0, #40
        ldmia   r0!, {r4, r5, r6, r7}
        vldm    r0!, {s16 - s31}
        sub     r0, r0, #64     // + 16 * 4 = 64 bytes
        // Return the result argument, or 1 if it is zero.
        mov     r0, r1
        bne     1f
        mov     r0, #1
1:
        bx      r3
        .size longjmp, . - longjmp
```
can you please fix the code so that it works ?

**Comment by ruben-ayrapetyan** [comment]
> can you please fix the code so that it works ?

@seanshpark, I would gladly do this, but before this I should finish some activities. I'll do this as soon as possible.

**Comment by ruben-ayrapetyan** [comment]
@seanshpark, I think that code from https://github.com/Samsung/jerryscript/issues/231#issuecomment-116652062 should work if buffer size is enough.

**Comment by seanshpark** [comment]
@ruben-ayrapetyan , thank you very much. I'll try with adding setjmp.h in nuttx include with the code #231 tomorrow morning.

**Comment by seanshpark** [comment]
It works with https://github.com/Samsung/jerryscript/issues/231#issuecomment-116652062 !

**Comment by ruben-ayrapetyan** [comment]
@seanshpark, it's great!

**Comment by seanshpark** [comment]
I think this issue can be closed cause changes are for nuttx and added to 20150706 patch
