### ISSUE TITLE
Generate builtin getters for Date object

### ISSUE THREAD

**Issue by szledan** [Samsung/jerryscript#233]
The Date Prototype Object  (15.9.5) has some getters (around 26), that are very similar. For now, I implemented most of them separately in [1]. Maybe we could generate them. The most different parts are in a try-catch block. 
Could you give some ideas how I should generate these getter functions.

Some typically differences:
* the helper functions return value is: int or ecma_number_t
* Every getter function has a simple and an UTC version.

CC: @egavrin @ruben-ayrapetyan  @galpeter @zherczeg @LaszloLango 

[1] https://github.com/szledan/jerryscript/commit/51275ff06474372660db783d5789834a351041f4

**Comment by galpeter** [comment]
Closing issue, as this was implemented in https://github.com/Samsung/jerryscript/pull/334 and landed in: https://github.com/Samsung/jerryscript/commit/8d7cdebee09d9fcccb85b47efa4e84341f065607
