### ISSUE TITLE
Implement ECMA262 RegExp builtin object and RegExp engine

### ISSUE THREAD

**Issue by LaszloLango** [Samsung/jerryscript#27]
Related ECMA2626 section: http://www.ecma-international.org/ecma-262/5.1/#sec-15.10.3

- [x] Regexp Builtin components
  - [x] Register the RegExp built-in object.
  - [x] RegExp(..)
    - [x] RegExp(pattern)
    - [x] RegExp(pattern, flag)
    - [x] RegExp(RegExp)
  - [x] new RegExp(..)
    - [x] RegExp(pattern)
    - [x] RegExp(pattern, flag)
    - [x] RegExp(RegExp)
  - [x] RegExp.prototype
  - [x] RegExp.prototype.constructor
  - [x] RegExp.prototype.exec(..)
  - [x] RegExp.prototype.test(..)
  - [x] RegExp.prototype.toString(..)
  - [x] RegExp.source
  - [x] RegExp.global
  - [x] RegExp.ignoreCase
  - [x] RegExp.multiline
  - [x] RegExp.lastIndex
- [x] Implement RegExp bytecode storage
  - Requirements
    - [x] Resize  automatically when it is needed
    - [x] Append and insert uint32 and uint8
    - [x] Read uint32 and uint8
    - [x] Advance in bytecode while reading
    - [x] Dump container (for debug)
- [x] Compile RegExp bytecode
  - Compile RegExp pattern to an internal bytecode to be able to run it efficiently.
    - [x] Disjunction
    - [x] Alternative
    - [x] Assertion
    - [x] Atom
      - [x] PatternCharacter
      - [x] .
      - [x] \ AtomEscape (depends on #49)
      - [x] CharacterClass
    - [x] Quantifier
- [x] Execute RegExp
  - Read the compiled bytecode and try to match.
    - [x] Disjunction
    - [x] Alternative
    - [x] Assertion
    - [x] Atom
      - [x] PatternCharacter
      - [x] .
      - [x] \ AtomEscape
      - [x] CharacterClass
    - [x] Quantifier
    - [x] Handle flags (depends on #49)
      - [x] Global
      - [x] IgnoreCase
      - [x] Multiline
    - [x] Set lastIndex property
    - [x] Set properties of the returned array object
- [x] Parse RegularExpressionLiterals and create a RegExp object.

**Comment by zherczeg** [comment]
Everything is implemented, so we can close this bug.
