### ISSUE TITLE
Add functionality to append or remove last element of ecma-collections

### ISSUE THREAD

**Issue by zherczeg** [Samsung/jerryscript#310]
Currently ecma collections has no append (update/remove) functionality. Append is required by JSON.

Test cases are required for testing append as well.

**Comment by ruben-ayrapetyan** [comment]
Blocks #311

**Comment by ruben-ayrapetyan** [comment]
Element removal interface is also necessary (https://github.com/Samsung/jerryscript/pull/509#issuecomment-127587829).

**Comment by galpeter** [comment]
Closing as this was implemented & merged into master
