### ISSUE TITLE
concatenating surrogates fails

### ISSUE THREAD

**Issue by zherczeg** [Samsung/jerryscript#346]
var str1 = "\ud801\udc00";
var str2 = "\ud801";
var str3 = "\udc00";
print(str1 == str2 + str3);

should be true, not false

Actually I need a similar technique for implementing toLowerCase/toUpperCase, and would like to mimic what the concatenation does. Unfortunately concatenation does not work at the moment.

**Comment by egavrin** [comment]
Works on master (f17f785b6ec0c71c2ef37e4e80a98aff1eff0963)
