### ISSUE TITLE
Internal value of Date.prototype should be NaN.

### ISSUE THREAD

**Issue by szledan** [Samsung/jerryscript#351]
### Test:
`assert (isNaN(Date.prototype.valueOf.call(Date.prototype)));`

### ECMA:
http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.5

**Comment by szledan** [comment]
:)

**Comment by galpeter** [comment]
Closing issue as this was fixed in: https://github.com/Samsung/jerryscript/commit/9c559216b7b72cf5073cc4dea644ae332d3c140b
