### ISSUE TITLE
Unicode support in implementation of parseInt

### ISSUE THREAD

**Issue by ruben-ayrapetyan** [Samsung/jerryscript#405]
Hello.

Implementation of `parseInt` (ecma-builtin-global.cpp) should be updated to use UTF-8 iterators for processing characters buffer.

Comment of @zherczeg in #394:
> Is this correct? If I understand correctly, we just pass a byte, rather than an uint16_t character. I think we should rewrite this to use the UTF iterators, since there are line terminators and white spaces outside of the [0-127] byte range.

**Comment by galpeter** [comment]
Closing as this is fixed now.
