### ISSUE TITLE
Out of memory error with JSON.stringify

### ISSUE THREAD

**Issue by renatahodovan** [Samsung/jerryscript#411]
###### Jerry version:
    Checked revision: abc2b55
    Build: debug.linux
###### OS: 
    Ubuntu 15.04, x86_64
###### Description:
Calling JSON.stringify with a not too big (length > 38) array ends in an out of memory error.
###### Test case:
```javascript
var a = ["a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a","a"];
print(JSON.stringify(a));
// a.length: 39
```

**Comment by rtakacs** [comment]
This happens during ecma_concat_ecma_strings. I think this bug is related to the core.

**Comment by ruben-ayrapetyan** [comment]
@rtakacs, the bug is related to `realloc_list` function (ecma-builtin-helpers-json.cpp).

**Comment by ruben-ayrapetyan** [comment]
Seems that calculation of block sizes and `current_p` / `block_end_p` pointers assumes that difference of pointers would be equal to arithmetic difference of addresses. Actually, value is the difference divided by sizeof (void*). Usage of incorrect pointers subsequently leads to overwrite of heap structures.

**Comment by rtakacs** [comment]
#543 will resolve the bug :)
