### ISSUE TITLE
Remove usage of isalpha and isdigit from JSON built-in's implementation

### ISSUE THREAD

**Issue by ruben-ayrapetyan** [Samsung/jerryscript#424]
Hello.

Currently, implementation of JSON built-in uses isalpha and isdigit functions.
Instead, helpers from lit_char should be used.

After the replacement is performed, `isalpha` and `isdigit` functions should be removed.

**Comment by akiss77** [comment]
There is a name clash with `isalpha` if compiler-default library is used for the build (on x86_64 Ubuntu 14.04.2 LTS with gcc 4.8.4). Is it worth reporting/fixing the issue (only 4 lines of changes) or should I wait for the replacement?

**Comment by zherczeg** [comment]
Fix: PR #484

**Comment by akiss77** [comment]
Fix landed, closing issue
