### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [Samsung/jerryscript#472]
Some parameters (like "[${CMAKE_BINARY_DIR}/generated.h](https://github.com/Samsung/jerryscript/blob/bc0ca7be5d1081e8a1115b870237f8d3f19b32d9/CMakeLists.txt#L92)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes. "CMake splits arguments unless you use quotation marks or escapes.").

**Comment by zherczeg** [comment]
We can reopen this issue if it is still valid.
