### ISSUE TITLE
Differences comparing to Duktape

### ISSUE THREAD

**Issue by drasko** [Samsung/jerryscript#494]
Hi,
can somebody please explain differences between JerryScript and Duktape (http://duktape.org/) project which is already used by many projects, notably AllJoyn, and why do we have to duplicate the work (in case that differences are not significant)?

BR,
Drasko

**Comment by lemmaa** [comment]
@drasko Nothing special, but there seems to be little difference in priority of design goal. Please reference (https://github.com/Samsung/jerryscript/issues/544).
Thanks!

**Comment by seanshpark** [comment]
maybe close this issue?

**Comment by drasko** [comment]
Yes, thanks. Closing now...
