### ISSUE TITLE
Dependency on tk

### ISSUE THREAD

**Issue by sragavan** [Samsung/jerryscript#516]
Hi,

Im trying to build this for Edison and I couldn't proceed,as it some point needs 'tk' which need xlib. Jerryscript needs vera++ and vera++ needs tk. I dont think xlib would be available on edison image any time. Is there a plan on how to go about this?

**Comment by egavrin** [comment]
@sragavan please try again after #517 PR.

vera++ is a part of prerequisites script, which is used to download and build tools needed for code checking. Engine itself has no dependencies on them.

**Comment by sragavan** [comment]
@egavrin Thanks for the rapid action. I will check it up.
