### ISSUE TITLE
Investigate possible ways to improve "GC start threshold" adjustment heuristics

### ISSUE THREAD

**Issue by ruben-ayrapetyan** [Samsung/jerryscript#535]
"GC start threshold" adjustment heuristics should be investigated to reduce number of those GC invocations that are most likely unnecessary.

See also: https://github.com/Samsung/jerryscript/pull/534#issue-99234304

**Comment by egavrin** [comment]
Fixed on master (f17f785b6ec0c71c2ef37e4e80a98aff1eff0963)
