### ISSUE TITLE
Add support of syntax error checking

### ISSUE THREAD

**Issue by sand1k** [Samsung/jerryscript#54]
- [X] implement setjmp / longjmp
 - [x] add checks into parsing of expression
  - [x] 11.1.5
  - [x] 11.3.1
  - [x] 11.3.2
  - [x] 11.4.1
  - [x] 11.4.4
  - [x] 11.4.5
  - [x] 11.13.1
  - [x] 11.13.2
  - [x] 12.2.1
  - [x] 12.10.1
  - [x] 12.14.1
  - [x] 13.1

**Comment by egavrin** [comment]
@sand1k please recheck this issue after unicode implementation
