### ISSUE TITLE
Enhance 'make log' info

### ISSUE THREAD

**Issue by sand1k** [Samsung/jerryscript#55]
- [ ] Add test262 pass rate information
- [ ] Provide binary size information for each configuration 
- [ ] Merge log information into tables:

|                    | peak parser consumption | byte-code size | peak runtime consumption (without bytecode) | peak overall consumption | rss |
|--------------------|-------------------------|----------------|---------------------------------------------|--------------------------|-----|
| benchmark suite 1: |                         |                |                                             |                          |     |
| bench1.js          |                         |                |                                             |                          |     |
| bench2.js          |                         |                |                                             |                          |     |
| bench3.js          |                         |                |                                             |                          |     |
|                    |                         |                |                                             |                          |     |
| benchmark suite 2: |                         |                |                                             |                          |     |

| stm32 mem limit    | 8kb | 32kb | 64kb | 128kb |
|--------------------|-----|------|------|-------|
| benchmark suite 1: |     |      |      |       |
| bench1.js          |     |      |      |       |
| bench2.js          |     |      |      |       |
| bench3.js          |     |      |      |       |
|                    |     |      |      |       |
| benchmark suite 2: |     |      |      |       |

Blocks: #56

**Comment by akosthekiss** [comment]
The build system underwent heavy modifications lately, therefore this old and abandoned issue is not applicable anymore.
