### ISSUE TITLE
error: control reaches end of non-void function

### ISSUE THREAD

**Issue by seanshpark** [Samsung/jerryscript#572]
Some functions like `lit_get_magic_string_utf8()` ends with 
```
  JERRY_UNREACHABLE ();
}
```
and does not return value. 
In this case without `-Wno-return-type` mips compiler fails with an `error: control reaches end of non-void function`. Should I use this option `-Wno-return-type` or should I add something like this?
```
  JERRY_UNREACHABLE ();
  return NULL; /* make compiler happy */
}
```

**Comment by egavrin** [comment]
This flag is useful, so I'd prefer to add `return NULL;`.

**Comment by ruben-ayrapetyan** [comment]
`JERRY_UNREACHABLE` macro calls `jerry_unreachable` function that is marked with `noreturn` attribute (`jerry_unreachable` leads to either `exit` or `abort`).
So, seems that the warning is false-positive.
To fix this, maybe, `while (true) {}` loop could be added after call to `jerry_unreachable` in the macro.

**Comment by seanshpark** [comment]
adding `while (true) {}` to end of `jerry_fatal()` works. 
there are `jerry_assert_fail()`, `jerry_unreachable()` and `jerry_unimplemented()` that calls `jerry_fatal()` and all of them has `noreturn` attribute.
@ruben-ayrapetyan , if you confirm I'll make a PR.

**Comment by egavrin** [comment]
@seanshpark @ruben-ayrapetyan 
```cpp
#define JERRY_UNREACHABLE() \
  do \
  { \
    jerry_unreachable (NULL, __FILE__, __func__, __LINE__); \
    __builtin_unreachable(); \
  } while (0)
```

**Comment by seanshpark** [comment]
@egavrin , that will change 6 lines in jrt.h, is it ok? :)

**Comment by egavrin** [comment]
@seanshpark :+1:

**Comment by seanshpark** [comment]
Close as #586 landed
