### ISSUE TITLE
Cross build is broken after #574

### ISSUE THREAD

**Issue by egavrin** [Samsung/jerryscript#577]
Seams that issue in this line:
```cpp
JERRY_ASSERT (dest_p - character_buffer == result_string_length);
```

**Comment by zherczeg** [comment]
What is the compiler error? Neither make precommit nor make push do not have any problem with it.

**Comment by zherczeg** [comment]
Is it a type conversion error?

**Comment by egavrin** [comment]
Yes, type conversion.

**Comment by zherczeg** [comment]
I don't see this error so I need your help. Please copy the compiler error here, and I will give you a speculative fix. Please try whether it works and then I can create a patch.

**Comment by egavrin** [comment]
Do you have cross toolchain? You can reproduce results with the following command:
`make release.linux   -j4 TOOLCHAIN="./build/configs/toolchain_linux_armv7l-el.cmake"`

I'll rebuilt and share output to you.

**Comment by zherczeg** [comment]
I have what is downloaded by precommit/push. It has cross compiler dependencies, but they work

**Comment by egavrin** [comment]
Please check
```
/home/user/jerry-gh/jerry-core/ecma/builtin-objects/ecma-builtin-helpers-date.cpp: 
In function ‘ecma_completion_value_t
ecma_date_value_to_string(ecma_number_t)’:
/home/user/jerry-gh/jerry-core/ecma/builtin-objects/ecma-builtin-helpers-date.cpp:1090:3: 
error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
```

**Comment by zherczeg** [comment]
ASSERT ((uint32_t) (dest_p - character_buffer) == result_string_length);

Does this fix it?

**Comment by sand1k** [comment]
@zherczeg, yes, it should fix the issue.
Please, check by running:
```
make release.linux -j4 TOOLCHAIN=./build/configs/toolchain_linux_armv7l-el.cmake
```

**Comment by zherczeg** [comment]
PR #582
