### ISSUE TITLE
Implement JSON object

### ISSUE THREAD

**Issue by rtakacs** [Samsung/jerryscript#61]
- [x] Register the JSON built-in object.
- [x] parse()
 - [x] implement a parser
 - [x] implement a lexer
 - [x] add support for reviver
- [x] stringify()
 - [x] simple values to JSON
 - [x] object values to JSON
 - [x] array values to JSON
 - [x] add support for replacer
 - [x] add support for spaces (formatting)

merge request: #168

**Comment by galpeter** [comment]
JSON landed in: https://github.com/Samsung/jerryscript/commit/d1a5f7fc87dd4a68434942c45d841d6585025d9d
