### ISSUE TITLE
Invalid source encoding error when using Hungarian characters

### ISSUE THREAD

**Issue by renatahodovan** [Samsung/jerryscript#613]
###### Jerry version:
    Checked revision: a26c454
    Build: debug.linux
###### OS: 
    Ubuntu 15.04, x86_64
###### Test case:
```javascript
a = "é"
```
###### Output:
```
ERROR: Ln 1, Col 1: Invalid source encoding
```

**Comment by egavrin** [comment]
Works on master (f17f785b6ec0c71c2ef37e4e80a98aff1eff0963)
