### ISSUE TITLE
arm build fail for assignment to bit field

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/jerryscript#634]
recent PR about snapshot introduces bit field assignment code.

``` header.is_run_global = is_for_global; ``` at 1605 in jerry.cpp
```tree->strict_mode = strict_mode; ``` at parser/js/scopes-tree.cpp

When cross-compiling jerry(inside IoT.js), it exits with the following msg :

/home/twoflower/usr/dev/harmony/iotjs_github/deps/jerry/jerry-core/jerry.cpp:1607:24: error: conversion to 'unsigned char:1' from 'uint32_t {aka unsigned int}' may alter its value [-Werror=conversion]
   header.is_run_global = is_for_global;
                        ^
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors

My arm-none-eabi-gcc version : gcc version 4.8.2 (4.8.2-14ubuntu1+6)

``` header.is_run_global = is_for_global?1:0; ``` makes compilation OK.  

Should I submit PR for this or Am I missing something ?

**Comment by chunseoklee** [comment]
Building jerry with ```make debug.mcu_stm32f4_cp``` works fine. 
Need to figure out why it does not work on IoT.js build setup.

**Comment by egavrin** [comment]
Fixed with NuttX configuration
