### ISSUE TITLE
Invalid left-hand-side expression

### ISSUE THREAD

**Issue by zherczeg** [Samsung/jerryscript#646]
```
b
(b) = c
```

The CBC parser correctly handles this, so it might not worth fix it at all. But I leave it here as a note.

**Comment by ruben-ayrapetyan** [comment]
There is development branch that contains an approach for general solution of references handling issues: https://github.com/Samsung/jerryscript/compare/Ruben-references-parser-dev

**Comment by LaszloLango** [comment]
works on current master (76b37f3)
