### ISSUE TITLE
Object literals in case selectors are not supported

### ISSUE THREAD

**Issue by renatahodovan** [Samsung/jerryscript#654]
###### Jerry version:
    Checked revision: 98fc409
    Build: debug.linux
###### OS: 
    Ubuntu 15.04, x86_64
###### Test case:
```javascript
switch (true) {
    case {"foo": "bar"}:
        break;
}
```
Output:
```
        break;
             ^
ERROR: Ln 3, Col 14: No corresponding statement for the break
```

According to ecma5, the expression above should be parsed (in spite of that the given clause value will never be equal to any switch condition).

**Comment by wateret** [comment]
@renatahodovan 
I think we can close this. Check out #666.

**Comment by egavrin** [comment]
Works on master (f17f785b6ec0c71c2ef37e4e80a98aff1eff0963)
