### ISSUE TITLE
if statement followed by a regex literal throws parse error

### ISSUE THREAD

**Issue by renatahodovan** [Samsung/jerryscript#655]
###### Jerry version:
    Checked revision: 98fc409
    Build: debug.linux
###### OS: 
    Ubuntu 15.04, x86_64
###### Test case:
```javascript
if (true) {}
/a/;
```
Output:
```
/a/;
^
ERROR: Ln 2, Col 1: Unknown token /
```

**Comment by wateret** [comment]
Closing as #660 landed.
