### ISSUE TITLE
Enabling setting MEM_HEAP_AREA_SIZE for linux host.

### ISSUE THREAD

**Issue by ILyoan** [Samsung/jerryscript#664]
On linux host machine, `CONFIG_MEM_HEAP_AREA_SIZE` would be set 256KB by default. I cannot find the way to set the configuration from CMake build system.

I would be useful to set the heap size for host machine so that we can test with memory consumption problem on host without flashing binary into target device.

**Comment by egavrin** [comment]
It is possible to specify heap size in this file: https://github.com/Samsung/jerryscript/blob/master/jerry-core/config.h#L45

**Comment by ILyoan** [comment]
@egavrin Yes, sure we can. but I think it would be better to set heap limit as build parameter, without touching source file.

**Comment by akosthekiss** [comment]
The new build system now allows passing `-DMEM_HEAP_SIZE_KB=...` to cmake, which will define the `CONFIG_MEM_HEAP_AREA_SIZE` macro for the compiler.
