### ISSUE TITLE
Unknown token error in the return statement

### ISSUE THREAD

**Issue by rtakacs** [Samsung/jerryscript#669]
<b>Jerry revision:</b>
<pre>08c618e</pre>

<b>Test case:</b>
```javascript
function f(){return}
```

It returns with <b>'ERROR: Ln 1, Col 20: Unknown token }'</b> however it is a valid JavaScript code.

<b>Expected behaviour:</b>
The functions should be parsed correctly that does nothing.

**Comment by wateret** [comment]
And I found more examples that have similar problem:
```javascript
switch (1) {
  case 1:
    break}
```

```javascript
while (true) {continue}
```
