### ISSUE TITLE
What version of ecmascript is supported in JerryScript?

### ISSUE THREAD

**Issue by gustavosbarreto** [Samsung/jerryscript#671]

**Comment by lemmaa** [comment]
Hi @gustavosbarreto, JerryScript currently supports ECMA Script v5.1 specification.

**Comment by cwong1** [comment]
Is there documentation tells what's left out from ECMA specification with the cp (compact profile) build?

**Comment by LaszloLango** [comment]
@cwong1, AFAIK there is no documentation. Compact profile is quite experimental at the moment. In compact profile all ECMA builtins and arguments object are disabled. You may interested in the following issue: #88
You can also check the https://github.com/Samsung/jerryscript/blob/master/tests/jerry-test-suite/compact-profile-list file. Those tests run in CP. Do you have any usecase already?
