### ISSUE TITLE
Jerry API for triggering GC.

### ISSUE THREAD

**Issue by ILyoan** [Samsung/jerryscript#672]
How about adding `void jerry_api_gc (void)` API for triggering GC.

**Comment by egavrin** [comment]
No objections, but for me this won't give us any profit it term of memory consumption since GC has pretty smart heuristics for triggering itself.

**Comment by ILyoan** [comment]
@egavrin Yes you are right.
I suggested this API because It would be helpful for tracing memory usage or profiling.

**Comment by LaszloLango** [comment]
Related PR (#685) was merged.
