### ISSUE TITLE
ecma_collection_chunk_t memory alignment

### ISSUE THREAD

**Issue by seanshpark** [Samsung/jerryscript#675]
While working with ESP8266(Xtensa chip) I got a odd exception error that I want to share and ask.
Error:
```
Fatal exception (9): 
epc1=0x402803a2
epc2=0x00000000
epc3=0x00000000
epcvaddr=0x3fff2862
depc=0x00000000
rtn_add=0x40275c55
```
`rtn_add=0x40275c55` seems to be return address which is, from the memory map, `vm_fill_params_list`.
`epc1=0x402803a2` seems to be the PC where it points somewhere in `ecma_append_to_values_collection`

I didn't see anything wrong with the code and it works fine for both x86 and arm.
I tracked the place and found it was the last line
```
values_p[pos_of_new_value_in_chunk] = ecma_copy_value (v, do_ref_if_object);
```
As I don't have any jtag tools, just old printf to see the value.
```
printf(">> %p %d\r\n", values_p, pos_of_new_value_in_chunk);
```
and got this.
```
>> 3fff2862 0
```

It's 3'rd byte with this 32bit core, maybe this can be the reason? so I changed the structure with padding.
```
typedef struct
 {
   /** Compressed pointer to next chunk */
   mem_cpointer_t next_chunk_cp;
   mem_cpointer_t dummy;
 
   /** Characters */
   lit_utf8_byte_t data[ sizeof (uint64_t) - sizeof (mem_cpointer_t) * 2 ];
 } ecma_collection_chunk_t;
```
And... It worked. But this will reduce 2 bytes... 

So I tried another one.
```
typedef struct
{
  /** Characters */
  lit_utf8_byte_t data[ sizeof (uint64_t) - sizeof (mem_cpointer_t) ];

  /** Compressed pointer to next chunk */
  mem_cpointer_t next_chunk_cp;
} ecma_collection_chunk_t;
```
And... this also worked.
I searched with `xtensa + misaligned` and found only there will be exception when misaligned read, and nothing more.

So the question, @egavrin, @ruben-ayrapetyan ,  
1) do you have any experience with such kind?
2) Is it OK to change like the second one?

**Comment by LaszloLango** [comment]
This issue is fixed in #733 (f574597a)
