### ISSUE TITLE
15.1.3 (URI Handling) chapter test262 failures

### ISSUE THREAD

**Issue by ruben-ayrapetyan** [Samsung/jerryscript#692]
Hello.

The following test262 tests related to 15.1.3 chapter are failing on current master (906558b8e94aa9118971188af9880eb47ff9b791):
- ch15/15.1/15.1.3/15.1.3.1/S15.1.3.1_A2.5_T1
- ch15/15.1/15.1.3/15.1.3.2/S15.1.3.2_A2.5_T1

**Comment by egavrin** [comment]
Works on master (f17f785b6ec0c71c2ef37e4e80a98aff1eff0963)
