### ISSUE TITLE
Logo creation

### ISSUE THREAD

**Issue by Seo-Young** [Samsung/jerryscript#702]
Our project does not have the official logo yet. Thus, I would like to suggest to open an issue for logo creation.
Please post ideas into this thread. If you have any logo images to suggest, feel free post them. 
You do not need to be a designer. If you can explain your idea, community can make it real image.
Every suggested ideas will be our logo candidates. 
Logo iterations also welcome.

I would like to open this issue for three weeks and gathering enough candidates. 
This issue will be closed at 11/25.
I will open a new issue for voting with candidates 11/26. 
And I guess we will meet the first day of December with our new logo. :)

**Comment by seanshpark** [comment]
Can we talk with MGM to use Jerry image?
Mix with JavaScript image found in the internet, in a yellow rounded rectangle with black silhouette of Jerry.

**Comment by Seo-Young** [comment]
![image](https://github-cloud.s3.amazonaws.com/assets%2F5035570%2F10958290%2Ff8a3f8be-83af-11e5-8788-c7992e97a3ec.png)

Is this the right image in your mind?
The distribution right had been moved to Warner Bros. since 1988. Do we have to ask them? Hum.. let's see.

**Comment by seanshpark** [comment]
YES! :clap:  also there can be also with whole body

**Comment by Seo-Young** [comment]
Some iterations
![image](https://github-cloud.s3.amazonaws.com/assets%2F5035570%2F10959945%2F0891406c-83c2-11e5-9213-00c4c3ac4095.png)

**Comment by Seo-Young** [comment]
![image](https://github-cloud.s3.amazonaws.com/assets%2F5035570%2F10960233%2Ff1e7096a-83c5-11e5-9712-89bed630389f.png)

![image](https://github-cloud.s3.amazonaws.com/assets%2F5035570%2F10960243%2F027e17a0-83c6-11e5-908e-bdc53ec94a01.png)

**Comment by akiss77** [comment]
Some hand drawings. Certainly not full-fledged ideas.
![collage_20151105083644686-1](https://cloud.githubusercontent.com/assets/9976482/10962891/08d34faa-839c-11e5-8542-fa7831fa50ad.jpg)

**Comment by ILyoan** [comment]
![jerry](https://cloud.githubusercontent.com/assets/2672194/10963531/72724c0c-83e4-11e5-88f2-18c471ef395f.png)

**Comment by ILyoan** [comment]
![iotjs](https://cloud.githubusercontent.com/assets/2672194/10963832/8f6a8584-83e6-11e5-9b62-ecb4620ddcee.png)

IoT.js logo is bonus :)

**Comment by zherczeg** [comment]
The last picture is quite similar to Mickey Mouse and I am sure Disney will not allow us to use it.

**Comment by Seo-Young** [comment]
Let's ask to Disney! :)

**Comment by ILyoan** [comment]
By the way, I would be unhappy if I was Disney and someone is asking me to allow using Mickey logo while call it Jerry :(

**Comment by ILyoan** [comment]
![jerry-8bit](https://cloud.githubusercontent.com/assets/2672194/10991527/56d663bc-84a1-11e5-911d-df886008057e.png)

**Comment by Seo-Young** [comment]
I've checked the JS logo. It is released under a MIT license so we can use it in our logo as we want. 
Refer to https://github.com/voodootikigod/logo.js

**Comment by Seo-Young** [comment]
![image](https://cloud.githubusercontent.com/assets/5035570/11057970/d2735d66-87d2-11e5-9dac-fe5cdfa50a7a.png)

![image](https://cloud.githubusercontent.com/assets/5035570/11057976/da4eac7a-87d2-11e5-83f3-17e11cab0fdb.png)

@akiss77 's hand drawings. I missed the tail of the latter one.

**Comment by idkiller** [comment]
![path3929-9-4](https://cloud.githubusercontent.com/assets/891887/11063899/ecd9373c-87fc-11e5-9e22-ae6090424996.png)

Drawing with Inkscape, Just "J" cheese with small rat.

**Comment by akanatov** [comment]
@idkiller if you put J-cheese under Jerry's right paw and S as $ (dollar) :-) under the left one - then it will be Java$cript :-)

**Comment by tczene** [comment]
![js](https://cloud.githubusercontent.com/assets/1426320/11091853/f3ab3736-887e-11e5-81c6-24b8b14b04bb.png)

**Comment by davidsz** [comment]
![logos3](https://cloud.githubusercontent.com/assets/4364601/11302106/a4d82762-8f9b-11e5-91b1-a07c75a1df63.png)

Some variations.
