### ISSUE TITLE
Change arguments of `assert` to explicit boolean values in internal test suite

### ISSUE THREAD

**Issue by ruben-ayrapetyan** [Samsung/jerryscript#716]
Some tests in Jerryscript's internal test suite that are currently not included into precommit testing contain code that provides non-boolean values to `assert` function.

Because current implementation of `assert` accepts only explicit boolean true values, the tests that pass non-boolean values, are currently failing during full run of internal test suite as described in #711.

Maybe, the tests should be updated like in https://github.com/Samsung/jerryscript/pull/498/files#diff-c7d78eb307700cc443dc3324384a4033 and included into precommit testing list.

**Comment by LaszloLango** [comment]
#814 is merged so we can close this issue.
