### ISSUE TITLE
Q. current internal encoding for lit_utf8_byte_t * ? 

### ISSUE THREAD

**Issue by chunseoklee** [Samsung/jerryscript#722]
I am working on encoding stuff for IoT.js.
I have a question on jerry encoding.  
Here is my question : which encoding is used  for ```lit_utf8_byte_t *``` ?  cesu8, utf8 or both ?

**Comment by dbatyai** [comment]
Strings are encoded internally as cesu8, even though it says utf8 in function names. See discussion about this [here](https://github.com/Samsung/jerryscript/pull/616#issuecomment-142548923).

**Comment by chunseoklee** [comment]
@dbatyai Thanys for help. 
I have 1 more q. 
``` ecma_string_to_utf8_string ````  returns utf8 string or cesu8 string ?

**Comment by dbatyai** [comment]
@chunseoklee, `ecma_string_to_utf8_string` returns a cesu8 encoded string as well.

**Comment by chunseoklee** [comment]
@dbatyai  It is strange. ```jerry_api_string_to_char_buffer``` for "\uD834\uDD1E(MUSICAL SYMBOL G CLEF' (U+1D11E))" seems to return data of 4 byte lengths which is illegal for cesu-8 encoding.

**Comment by chunseoklee** [comment]
@dbatyai I found the reason why. Current iot.js's jerry submodule is on commit 08c6. But cesu8 patch were merged later.

**Comment by chunseoklee** [comment]
On latest commit, ```jerry_api_string_to_char_buffer``` returns cesu encoded format string. 
I will close this issue.
