### ISSUE TITLE
Timeout value in run-test-suite-test262.sh

### ISSUE THREAD

**Issue by wateret** [Samsung/jerryscript#728]
I found that with no timeout, Jerry passes a few more cases than with timeout.
Currently Timeout is 5s, but some cases take way longer than 5s but it passes.
I think we should increase timeout value or get rid of timeout.

Here are some of the tests that take long but pass.
* ch15/15.10/15.10.2/15.10.2.12/S15.10.2.12_A1_T1
* ch15/15.10/15.10.2/15.10.2.12/S15.10.2.12_A2_T1

**Comment by LaszloLango** [comment]
@wateret, if it is still an issue on the current master, then please create a PR with an appropriate timeout value.

**Comment by zherczeg** [comment]
Invalid now.
