### ISSUE TITLE
Please vote for logo

### ISSUE THREAD

**Issue by Seo-Young** [Samsung/jerryscript#755]
We've got diverse logo candidates. (We have 8 candidates)
Now, it's time to choose. :)
Please vote for JerryScript logo as follows; 
  - Give comment with the number of candidate.
  - You can pick two logo candidates up. 
  - This voting will be closed at 7:00 UTC on 12/4(Friday)

(1)
![image](https://cloud.githubusercontent.com/assets/5035570/11464860/1dfe7b90-9777-11e5-8d0c-d347ac3724fe.png)
![image](https://cloud.githubusercontent.com/assets/5035570/11464867/2d825eec-9777-11e5-949f-b040371045c5.png)
![image](https://cloud.githubusercontent.com/assets/5035570/11464870/32ef1d5c-9777-11e5-8c59-4917f59ce8e8.png)
. This has some iterations.
. This has one issue on Jerry. I haven't get the confirmation on use from Warner Bros. yet.(still on waiting.... ;( )

(2)
![image](https://cloud.githubusercontent.com/assets/5035570/11464895/68ab03ca-9777-11e5-8c04-3e4141039ae4.png)

(3)
![image](https://cloud.githubusercontent.com/assets/5035570/11464900/6d4e73bc-9777-11e5-9e83-b055a4209552.png)

(4)
![image](https://cloud.githubusercontent.com/assets/5035570/11464903/7336bdb6-9777-11e5-8a95-af6e12c7b45d.png)

(5)
![image](https://cloud.githubusercontent.com/assets/5035570/11464906/7bb77bf6-9777-11e5-8175-c1b2893a3666.png)

(6)
![image](https://cloud.githubusercontent.com/assets/5035570/11464919/8c722d10-9777-11e5-84cc-d39f78ab1d35.png)

(7) 
![image](https://cloud.githubusercontent.com/assets/5035570/11464926/9bfeffe2-9777-11e5-8923-8aa554e1509f.png)

(8)
![image](https://cloud.githubusercontent.com/assets/5035570/11464932/a8dcc762-9777-11e5-9b29-0fb006a1ed68.png)
![image](https://cloud.githubusercontent.com/assets/5035570/11464934/ad029eac-9777-11e5-95cc-1e4e32c3ab01.png)
. This has some iterations

**Comment by chunseoklee** [comment]
4

**Comment by Seo-Young** [comment]
8

**Comment by egavrin** [comment]
5

**Comment by fivdi** [comment]
Although I think 8 looks the best, I'd pick the 3rd variant of 1 due to its clear association with JavaScript.

**Comment by seanshpark** [comment]
1, 8

**Comment by lemmaa** [comment]
8-4

in 

0
1,2,3,4,5,6

**Comment by sand1k** [comment]
1, 8

**Comment by zherczeg** [comment]
8

**Comment by LaszloLango** [comment]
8

**Comment by ruben-ayrapetyan** [comment]
8 (version 5)

**Comment by renatahodovan** [comment]
8

**Comment by tczene** [comment]
8

**Comment by bzsolt** [comment]
8

**Comment by akiss77** [comment]
8 [bottom line 3rd from left], 4
(extra vote on the third place: 1 [topmost])

**Comment by minjung978** [comment]
8

**Comment by wateret** [comment]
8

**Comment by Boxie5** [comment]
6

**Comment by rapportyou** [comment]
5 looks good

**Comment by rtakacs** [comment]
8

**Comment by lvidacs** [comment]
8 (5th version in the bottom line) and 6

**Comment by Seo-Young** [comment]
Share current status.
![image](https://cloud.githubusercontent.com/assets/5035570/11522774/89483b4c-98fe-11e5-8786-8b36aee02f3e.png)

**Comment by idkiller** [comment]
8 :+1:

**Comment by Seo-Young** [comment]
Time's up! 

Now, you can see the result. :)  
![image](https://cloud.githubusercontent.com/assets/5035570/11584129/9450acfc-9aa4-11e5-848b-054b0d071bec.png)

But the selective one has variations so we need following decision that which one will be the main logo. 
![image](https://cloud.githubusercontent.com/assets/5035570/11584224/77eb9904-9aa5-11e5-8c2a-75ebcdc9856d.png)
With these, non selected can be used as iterations for the project. But if you would like to suggest remove any image from iterations, feel free to talk.

**Comment by Seo-Young** [comment]
1

**Comment by idkiller** [comment]
6 :+1:

**Comment by fivdi** [comment]
1

**Comment by akiss77** [comment]
3

**Comment by zherczeg** [comment]
6 we need the tail :)

**Comment by ruben-ayrapetyan** [comment]
4, 5

**Comment by egavrin** [comment]
4,5

Noooo, tail looks ugly!

**Comment by fivdi** [comment]
@ruben-ayrapetyan @egavrin during the second round of voting it's only possible to vote for one logo :)

**Comment by davidsz** [comment]
Maybe it's a bit late to clarify, but we can easily combine these iterations. For example, I would prefer the first logo without tail:
![logos4](https://cloud.githubusercontent.com/assets/4364601/11589900/8e1e469a-9a8c-11e5-862e-d901b460afe8.png)

**Comment by rtakacs** [comment]
8

**Comment by LaszloLango** [comment]
4,5

**Comment by bzsolt** [comment]
3

**Comment by lemmaa** [comment]
7

**Comment by wateret** [comment]
3,4

**Comment by seanshpark** [comment]
7

**Comment by Seo-Young** [comment]
@ruben-ayrapetyan @egavrin @LaszloLango @wateret Please re-vote. In this turn, you can pick only one. 
@davidsz So, is your decision 7? without tail?
@lemmaa You picked up 7, correct?

When everything are cleared. I will close this issue.

**Comment by lemmaa** [comment]
@Seo-Young Yes, 7!

**Comment by ruben-ayrapetyan** [comment]
5

**Comment by wateret** [comment]
3

**Comment by davidsz** [comment]
@Seo-Young Yes, 7 :)

**Comment by egavrin** [comment]
7

**Comment by LaszloLango** [comment]
4

**Comment by sand1k** [comment]
4

**Comment by Seo-Young** [comment]
Here's the result. :)
1 and 8 are same one so integrated.
![image](https://cloud.githubusercontent.com/assets/5035570/11641928/6966bb80-9d7e-11e5-99bf-75c2dce8d9f0.png)
If anyone would like to change your mind, please comment until today UTC 23:00. If not, we need other following voting.

**Comment by seanshpark** [comment]
7 --> 1
I like the tail :)

**Comment by wateret** [comment]
~~3~~ -> 4

Sorry for the tail.

**Comment by ruben-ayrapetyan** [comment]
5 -> 4

**Comment by zherczeg** [comment]
my only problem with 4 that people will think this is the moon js :)

**Comment by seanshpark** [comment]
> moon js :)

um... how about cut the cheese in half and fill only half of the circle, with some tilt, like the one filled S in 1 and 7

**Comment by zherczeg** [comment]
or making it square with holes perhaps

**Comment by seanshpark** [comment]
https://www.youtube.com/watch?v=T0qagA4_eVQ 
moon is cheese :)

**Comment by lemmaa** [comment]
FYI

In history of JerryScript, cheese is used for naming the IR, originate from @egavrin 's document, the `high-fat cheese IR` and the `low-fat cheese IR`. So, cheese inside 'JS' is reasonable for me, but 'JS' on the cheese is not. :)

**Comment by egavrin** [comment]
7

**Comment by idkiller** [comment]
In my Opinion, thick border makes the cheese to strange.
I think If whole JS  glyph is cheese, it looks better.

**Comment by Seo-Young** [comment]
![image](https://cloud.githubusercontent.com/assets/5035570/11671446/c4d7ee80-9e4b-11e5-865c-dce843ebc6b1.png)
The winner is 4! :dango: 
With above comments, I draw some variations. Which one is better?
![image](https://cloud.githubusercontent.com/assets/5035570/11671673/59b791bc-9e4d-11e5-89d5-c76d4b6bd708.png)

**Comment by seanshpark** [comment]
Yeah~~

> Which one is better?

the first one. (second has a bite which reminds of some company)

**Comment by Seo-Young** [comment]
Additionally, I suggest to release our logo under MIT License, when it's finally decided. 
Please let me know your opinions.

**Comment by lemmaa** [comment]
1

**Comment by egavrin** [comment]
1

**Comment by GrowingM** [comment]
The first one.

**Comment by ruben-ayrapetyan** [comment]
1

**Comment by bzsolt** [comment]
1.

**Comment by sand1k** [comment]
1

**Comment by fivdi** [comment]
1

**Comment by LaszloLango** [comment]
1

**Comment by davidsz** [comment]
With rounded square background:
![rounded_square_1](https://cloud.githubusercontent.com/assets/4364601/11686718/c42f1d28-9e82-11e5-9d76-e6b836c31679.png)

**Comment by zherczeg** [comment]
Hm looks good. I would prefer this one.

**Comment by egavrin** [comment]
Square moon?

**Comment by zherczeg** [comment]
I would prefer to remove the moon from the picture. This should be obviously a cheese (which is a reference to a mouse).

**Comment by lemmaa** [comment]
@davidsz How about pie sliced cheese?

**Comment by Seo-Young** [comment]
@davidsz Would you draw pie sliced cheese?
I also like rounded square better.

**Comment by seanshpark** [comment]
:+1:  to rounded square :)

**Comment by LaszloLango** [comment]
rounded square looks better to me too.

**Comment by davidsz** [comment]
@lemmaa @Seo-Young  I'm trying to imagine it, but I can't. The hungarian people are associating the triangle shaped cheese with their popular Bear Cheese. :)
![macko preview](https://cloud.githubusercontent.com/assets/4364601/11715359/98c9da82-9f41-11e5-8be5-c0ec4e85b243.JPG)

**Comment by egavrin** [comment]
@davidsz "Swiss cheese rounds" shows the best results:
![swiss cheese](http://footage.framepool.com/shotimg/953174515-cheese-board-cheese-with-holes-swiss-cheese-cheese-knife.jpg)
![mouse](http://static.guim.co.uk/sys-images/Guardian/Pix/pictures/2015/5/28/1432824969694/0446a1d8-9b17-4163-8aa8-e38f3a359ee3-2060x1236.jpeg)
![round](http://www.igourmet.com/images/topics/jarlsberg.jpg)
![round2](http://www.winesofcanada.com/images/cheese_jarlsberg.jpg)

**Comment by davidsz** [comment]
![slice_1](https://cloud.githubusercontent.com/assets/4364601/11717934/b18d771a-9f53-11e5-8858-329c61bb1358.png)

![slice_2](https://cloud.githubusercontent.com/assets/4364601/11717936/b5a0b240-9f53-11e5-8782-5a2745999941.png)

**Comment by Seo-Young** [comment]
@davidsz Thanks for your effort!. I like rounded square better. :)
![image](https://cloud.githubusercontent.com/assets/5035570/11732307/34407b5c-9fe6-11e5-8329-8758849d33b4.png)
Cute mouse! :D

**Comment by wateret** [comment]
pacman js? (just kidding!)

I'd prefer rounded square one.

**Comment by seanshpark** [comment]
Pie slice looks nice  
![jerryscript-pie-256](https://cloud.githubusercontent.com/assets/4616940/11735987/64e9c07c-a00b-11e5-9f80-b156ca1a1ee1.png)

**Comment by zherczeg** [comment]
I would still prefer the rounded. Perhaps it would be good to restart the voting for these 3 (circle, rounded rect and slice cheese).

**Comment by LaszloLango** [comment]
The slice cheese is like an arrow that points down, so it has a negative meaning.

**Comment by kkristof** [comment]
@LaszloLango for me it rather seems to resemble a slice of pizza or a crest shield (which is cool), but I haven't studied graphic design yet :)

**Comment by egavrin** [comment]
I'd agree with @LaszloLango - slice of cheese pointing down has negative meaning. Maybe replace slice with shield?

**Comment by kkristof** [comment]
@egavrin, something like the html5 logo?
http://www.w3.org/html/logo

**Comment by zherczeg** [comment]
How the shield is connected to Jerry?

**Comment by egavrin** [comment]
@kkristof yes, like that.

![logos](http://html5beginners.com/wp-content/uploads/2014/09/js.png)

**Comment by Seo-Young** [comment]
Do we need another voting?

**Comment by lemmaa** [comment]
@maxogden You may interest in this topic. :)

**Comment by maxogden** [comment]
There is of course my satire entry:

![logo](http://maxogden.com/media/jerryscript.png)

However I think this cannot be used because of the original:

![seinfeld](http://vignette2.wikia.nocookie.net/seinfeld/images/5/56/Seinfeld-logo.jpg/revision/latest?cb=20110324171835)

:)

**Comment by Seo-Young** [comment]
OK. Let's finish this issue. 
![image](https://cloud.githubusercontent.com/assets/5035570/11972720/9651c97a-a993-11e5-805f-b4d0d6c8a564.png)
Please pick up. You have just one ticket for this.  This issue will be closed 24 hours later.

**Comment by sangbae** [comment]
3   ;)

**Comment by fivdi** [comment]
2

**Comment by Seo-Young** [comment]
2

**Comment by wateret** [comment]
2

**Comment by zherczeg** [comment]
2

**Comment by seanshpark** [comment]
2

**Comment by ruben-ayrapetyan** [comment]
2

**Comment by rtakacs** [comment]
2

**Comment by GrowingM** [comment]
2

**Comment by egavrin** [comment]
2

**Comment by bzsolt** [comment]
1. (against the wind :))

**Comment by akiss77** [comment]
same here: 1

**Comment by lemmaa** [comment]
1 :)

**Comment by sand1k** [comment]
3

**Comment by Seo-Young** [comment]
Thank you for all your efforts. It's decided!!!!!!
https://cloud.githubusercontent.com/assets/4364601/11686718/c42f1d28-9e82-11e5-9d76-e6b836c31679.png

**Comment by lemmaa** [comment]
Congratulations! Merry Christmas~

**Comment by davidsz** [comment]
@Seo-Young Sorry for the late reaction. Here you go:
[rounded_square_logo.zip](https://github.com/Samsung/jerryscript/files/79818/rounded_square_logo.zip)

**Comment by Seo-Young** [comment]
@davidsz  Thanks too much for your effort!!!
