### ISSUE TITLE
Idea for API improvement

### ISSUE THREAD

**Issue by egavrin** [Samsung/jerryscript#770]
> I did a little exploration in jerryscript and IoT.js and noticed that IoT.js uses jerry_api_value_t structure defined in JerryScript API by accessing its members directly to do type checking and value retrieval activities. It is done through fuction-like macros defined in iotjs_binding.cpp: JVAL_IS_NULL, JVAL_IS_STRING, JVAL_TO_NUMBER, etc.
What is your opinion about this solution?
Maybe, it would be worthwhile to refine the JerryScript API by providing type checker and value retrieval functions to struct jerry_api_value_t in order to avoid the direct access of its internal structure in IoT.js. This can result clearer and more maintainable code that facilitates the future developments.

by @ktorpi

**Comment by lemmaa** [comment]
+1, https://github.com/Samsung/jerryscript/issues/711

**Comment by seanshpark** [comment]
+1

**Comment by LaszloLango** [comment]
Related PRs: #788, #810
