### ISSUE TITLE
Array performance + Crash

### ISSUE THREAD

**Issue by obastemur** [Samsung/jerryscript#778]
```
var arr=[];for(var i=0;i<1e5;i++)arr[i] = i%40
```

Script above takes almost 5 seconds to run on Azure small VM. Did not check the implementation yet but assuming an optimization here is possible.

**Comment by obastemur** [comment]
BTW;  the script above crashes for anything beyond 1e4 without any warning.

**Comment by wateret** [comment]
With debug build, Jerry prints `Error: ERR_OUT_OF_MEMORY` before crash. That's because maximum heap size of `jerryscript` is only 256KB. A primitive number value takes 8 bytes, so 100000 elements will require around 800KB.

**Comment by obastemur** [comment]
Preferred action could be `throwing a JS exception`
