### ISSUE TITLE
a broken page in the project home.

### ISSUE THREAD

**Issue by sjang** [Samsung/jerryscript#779]
Hi.

I am looking into the jerryscirpt thesedays.
I found a broken page today.

The page is the HOWTO of the jerryscript.
http://samsung.github.io/jerryscript/how-to/

The section, "How to Setup Recommended Prerequisites", has a broken link.
"Currently, ...
Additionaly, it’ll be useful to read >>> Prerequisites<<< wiki page, also."

"Prerequisites" is a link which has no page.

Thank you~

**Comment by egavrin** [comment]
Thank you for reporting. I'll fix it today.
