### ISSUE TITLE
Integrity checks in snapshot load routines

### ISSUE THREAD

**Issue by ruben-ayrapetyan** [Samsung/jerryscript#802]
Hello.

We need to add integrity checks to snapshot loader to ensure that an incorrectly composed snapshot wouldn't lead to memory corruption or other issues during the load procedure.

**Comment by egavrin** [comment]
It should verify checksum and engine's version at least.

**Comment by ruben-ayrapetyan** [comment]
There is snapshot version field in current version of snapshot header that is checked upon load.

**Comment by egavrin** [comment]
So, what about adding checksum?)

**Comment by ruben-ayrapetyan** [comment]
I think that this is good idea, but the checksum comparison wouldn't catch errors in case snapshot is intentionally malformed.

**Comment by egavrin** [comment]
Such issues can be checked only with appropriate testing, i.e snapshot can successfully pass internal test-suite and test262.

**Comment by ruben-ayrapetyan** [comment]
@egavrin, could you, please, clarify what kind of issues do you mean?

**Comment by ruben-ayrapetyan** [comment]
There was an offline discussion on the issue and we've concluded that this is issue is about integrity checks that should guarantee that only snapshot images that could be successfully read in conformity to the current snapshot format, should be considered correct by snapshot loader, and all other snapshot images should lead to correct indication of inconformity by the loader, without any memory corruptions or produce of incorrect run-time structures etc.

**Comment by LaszloLango** [comment]
@egavrin, @ruben-ayrapetyan, @zherczeg, can we close this issue?

**Comment by zherczeg** [comment]
I think we could think about this later for untrusted snapshots, but currently all snapshots are trusted. I close this for now, but it can be reopened later.
