### ISSUE TITLE
This example "Step 4. Interaction with JavaScript environment" has some error.

### ISSUE THREAD

**Issue by iamblue** [Samsung/jerryscript#817]
1.'jerry_api_value_t' has no member named 'string_p'
   val.string_p = str_val_p;
2. undefined reference to `jerry_api_get_global_object'

**Comment by iamblue** [comment]
I fix this here: https://github.com/Samsung/jerryscript/pull/818

**Comment by LaszloLango** [comment]
Related PR: #1046
