### ISSUE TITLE
Nominating Zsolt Borbely (bzsolt) for Committer status

### ISSUE THREAD

**Issue by zherczeg** [Samsung/jerryscript#842]
Hi,

I would like to nominate Zsolt Borbely to becoma a committer. His non-trivial patches are:

#78 Implemented Array.prototype.slice().
#86 Implement Array.prototype.splice().
#99 Implement Object.prototype.propertyIsEnumerable().
#138 Implement String.prototype.slice()
#163 Implement Function.prototype.apply()
#196 Fix the indexing of Array builtin functions.
#321 Implement Function.prototype.bind function
#386 Implement String.prototype.localeCompare function
#530 Implement String.prototype.split function
#729 Add option to enable all-in-one build mode

Any seconds?

**Comment by galpeter** [comment]
+1 (also afaik he also worked on the CBC parts)

**Comment by LaszloLango** [comment]
+1

**Comment by Seo-Young** [comment]
If there isn't any other opinions, let's go for next(put his name on committer list).

**Comment by zherczeg** [comment]
Added to: https://github.com/Samsung/jerryscript/wiki/Assigned-people
