### ISSUE TITLE
Reduce prerequisite dependencies?

### ISSUE THREAD

**Issue by akiss77** [Samsung/jerryscript#844]
In our development docs we state that Ubuntu is the supported dev platform, and there are already packages that must be installed via the distro's package manager, i.e., with apt-get. Still, vera++ and cppcheck tools are downloaded and installed with tools/prerequisites.sh into a local subdir, although they are present in Ubuntu's package repositories. Is there any reason not to list them simply in the dev docs as dependencies and remove their setup logic from prerequisites.sh?

(Happy to propose a PR if we reach consensus.)

**Comment by LaszloLango** [comment]
I prefer distro's packages. We don't apply custom changes on those tools, so it is not necessary to build them from source. As far as I know we use simple release source packages for the builds. So +1 to reduce prerequisite dependencies.
