### ISSUE TITLE
Should we keep external magic string support?

### ISSUE THREAD

**Issue by bzsolt** [Samsung/jerryscript#922]
Let's start a discussion about external magic string support, because there are some related functions,
but they aren't used currently (e.g.```ecma_is_ex_string_magic```, ```ecma_is_ex_string_magic_longpath```).
Now we can just register external magic strings, but they aren't accesssible through the API.
Is there anybody who uses, or plans to use this feature?

**Comment by akiss77** [comment]
IoT.js uses external magic strings but only the `jerry_register_external_magic_strings` function (in  iotjs/src/iotjs_string_ext.cpp). It would be interesting to see how its memory consumption would change without those magic strings.

**Comment by zherczeg** [comment]
I would rather keep it (or a special version of it). However, it should be automatically generated from snapshot. This would reduce the string memory consumption a lot. I would like to work on it if noone else is interested.
